apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: sales-rep-ai-ns # Ensure this matches the namespace created in 01-namespace.yaml
data:
  # Non-sensitive backend configurations
  NODE_ENV: "production"
  PORT: "3000" # Default NestJS port, confirm if different
  CORS_ORIGIN: "http://localhost:5173" # Placeholder, adjust as necessary for your production frontend URL or allow multiple origins

  # Add other non-sensitive environment variables from backend/.env here if any

  # IMPORTANT: Sensitive values like DATABASE_URI, ABLY_API_KEY, OPENAI_API_KEY,
  # and any other secrets will be stored in a Kubernetes Secret, not in this ConfigMap.
  # Example (these are placeholders and should be managed via Secrets):
  # DATABASE_URI: "placeholder-db-uri"
  # ABLY_API_KEY: "placeholder-ably-key"
  # OPENAI_API_KEY: "placeholder-openai-key"
  # OPENAI_MODEL: "gpt-4.1-mini" # This can also be in a configmap if not sensitive